const Data = [
  {
    SchemeID: 4,
    SchemeName: "UKTSA",
    SchemeDescription: "Trading Standards Approved",
    SchemePassingScore: 0,
    SchemeTotalScore: 218,
    SchemeIsActive: true,
    Sections: [
      {
        SectionID: 39,
        SectionIDParent: 0,
        SectionCode: "YD",
        SectionName: "Your Documents",
        SectionHeaderDescription: null,
        SectionFooterDescription: null,
        SectionSortOrder: 8,
        Questions: [
          {
            QuestionsID: 799,
            QuestionsIDParent: 777,
            QuestionsCode: null,
            QuestionsText: null,
            QuestionsSortOrder: 56,
            QuestionsScore: 1,
            QuestionsMandatory: false,
            QuestionsHelpText: null,
            QuestionsAutoFillAnswer: true,
            QuestionsDefaultValue: null,
            QuestionsDownloadLink: null,
            QuestionsOptionAlignment: 0,
            QuestionsDownloadLinkLabel: null,
            QuestionsAllowCondition: null,
            QuestionsAllowConditionValue: null,
            QuestionsOptionsColumn: 0,
            QuestionsMonitor: false,
            QuestionsIsGeographicalRegion: false,
            QuestionsIsSkillLots: false,
            QuestionsIdMonitorDocumentType: null,
            ControlID: 10,
            ControlName: "File",
            QuestionLabel: "Photo ID",
            QuestionHeaderDescription: null,
            QuestionFooterDescription: null,
            QuestionLabelPosition: 1,
            AutoFillAnswer: true,
            IdMonitorDocumentType: null,
            OptionsColumn: 0,
            AllowConditionValue: null,
            DefaultValue: null,
            AllowCondition: null,
            OptionAlignment: 0,
            // Answer: `/Dropbox/uploads/Organisation_JNMNLPJ8/Scheme_JNKQEMC8/Section_JNLRFPN4/jsonformatter_638373569567967652.txt`,
            Answer: "",

            ControlHelpText: null,
            ControlOption: null,
          },
          {
            QuestionsID: 744,
            QuestionsIDParent: 0,
            QuestionsCode: "Q1",
            QuestionsText:
              "Name of the business (registered name as shown on your accounts.) If you trade under a different name please add T/A and the name to this box you trade as",
            QuestionsSortOrder: 2,
            QuestionsScore: 1,
            QuestionsMandatory: true,
            QuestionsHelpText: null,
            QuestionsAutoFillAnswer: true,
            QuestionsDefaultValue: null,
            QuestionsDownloadLink: null,
            QuestionsOptionAlignment: 0,
            QuestionsDownloadLinkLabel: null,
            QuestionsAllowCondition: null,
            QuestionsAllowConditionValue: null,
            QuestionsOptionsColumn: 0,
            QuestionsMonitor: false,
            QuestionsIsGeographicalRegion: false,
            QuestionsIsSkillLots: false,
            QuestionsIdMonitorDocumentType: null,
            ControlID: 1,
            ControlName: "Text",
            QuestionLabel: null,
            QuestionHeaderDescription: null,
            QuestionFooterDescription: null,
            QuestionLabelPosition: 1,
            AutoFillAnswer: true,
            IdMonitorDocumentType: null,
            OptionsColumn: 0,
            AllowConditionValue: null,
            DefaultValue: null,
            AllowCondition: null,
            OptionAlignment: 0,
            Answer: "Testing Name of the business",
            ControlHelpText: null,
            ControlOption: null,
          },
        ],
      },
    ],
  },
];

export default Data;
// Answer: `/Dropbox/uploads/Organisation_JNMNLPJ8/Scheme_JNKQEMC8/Section_JNLRFPN4/jsonformatter_(2)_638373569527935288.txt|/Dropbox/uploads/Organisation_JNMNLPJ8/Scheme_JNKQEMC8/Section_JNLRFPN4/jsonformatter_638373569567967652.txt|/Dropbox/uploads/Organisation_JNMNLPJ8/Scheme_JNKQEMC8/Section_JNLRFPN4/testingImg_638373569622693345.jpg|/Dropbox/uploads/Organisation_JNMNLPJ8/Scheme_JNKQEMC8/Section_JNLRFPN4/jsonformatter_638373569652444726.txt`,
