const Data = [
  {
    SchemeID: 4,
    SchemeName: 'UKTSA',
    SchemeDescription: 'Trading Standards Approved',
    SchemePassingScore: 0,
    SchemeTotalScore: 218,
    SchemeIsActive: true,
    Sections: [
      {
        SectionID: 39,
        SectionIDParent: 0,
        SectionCode: 'YD',
        SectionName: 'Your Documents',
        SectionHeaderDescription: null,
        SectionFooterDescription: null,
        SectionSortOrder: 8,
        Questions: [
          {
            Answer: '20/12/2066',
            QuestionsID: 699,
            QuestionsIDParent: 0,
            QuestionsCode: null,
            QuestionsText: null,
            QuestionsSortOrder: 1,
            QuestionsScore: 1,
            QuestionsMandatory: true,
            QuestionsHelpText: null,
            QuestionsAutoFillAnswer: true,
            QuestionsDefaultValue: null,
            QuestionsDownloadLink: null,
            QuestionsOptionAlignment: 0,
            QuestionsDownloadLinkLabel: null,
            QuestionsAllowCondition: null,
            QuestionsAllowConditionValue: null,
            QuestionsOptionsColumn: 0,
            QuestionsMonitor: false,
            QuestionsIsGeographicalRegion: false,
            QuestionsIsSkillLots: false,
            QuestionsIdMonitorDocumentType: null,
            QuestionHeaderDescription:
              '<span class="text-danger">*</span> Please provide / Upload a copy of your complaint handling policy or details of how you handle complaints.',
            QuestionFooterDescription: null,
            QuestionLabel: null,
            QuestionLabelPosition: 1,
            ControlID: 5,
            ControlName: 'Date',
            ControlHelpText: null,
          },
          {
            Answer: 'from apis',
            QuestionsID: 700,
            QuestionsIDParent: 1015,
            QuestionsCode: null,
            QuestionsText: null,
            QuestionsSortOrder: 1,
            QuestionsScore: 1,
            QuestionsMandatory: true,
            QuestionsHelpText: null,
            QuestionsAutoFillAnswer: true,
            QuestionsDefaultValue: null,
            QuestionsDownloadLink: null,
            QuestionsOptionAlignment: 0,
            QuestionsDownloadLinkLabel: null,
            QuestionsAllowCondition: null,
            QuestionsAllowConditionValue: null,
            QuestionsOptionsColumn: 0,
            QuestionsMonitor: false,
            QuestionsIsGeographicalRegion: false,
            QuestionsIsSkillLots: false,
            QuestionsIdMonitorDocumentType: null,
            QuestionHeaderDescription: '',
            QuestionFooterDescription: null,
            QuestionLabel: null,
            QuestionLabelPosition: 1,
            ControlID: 4,
            ControlName: 'File',
            ControlHelpText: null,
            QuestionControlOption: null,
          },
          {
            Answer: 'this text form apis',
            QuestionsID: 701,
            QuestionsIDParent: 1016,
            QuestionsCode: null,
            QuestionsText: null,
            QuestionsSortOrder: 5,
            QuestionsScore: 1,
            QuestionsMandatory: true,
            QuestionsHelpText: null,
            QuestionsAutoFillAnswer: true,
            QuestionsDefaultValue: null,
            QuestionsDownloadLink: null,
            QuestionsOptionAlignment: 0,
            QuestionsDownloadLinkLabel: null,
            QuestionsAllowCondition: null,
            QuestionsAllowConditionValue: null,
            QuestionsOptionsColumn: 0,
            QuestionsMonitor: false,
            QuestionsIsGeographicalRegion: false,
            QuestionsIsSkillLots: false,
            QuestionsIdMonitorDocumentType: null,
            QuestionHeaderDescription: '',
            QuestionFooterDescription: null,
            QuestionLabel: null,
            QuestionLabelPosition: 1,
            ControlID: 1,
            ControlName: 'Text',
            ControlHelpText: null,
            QuestionControlOption: null,
          },
        ],
      },
    ],
  },
];

export default Data;
